gyro
feagi/controllers pull request #24
Opened 2024-10-19 15:11 UTC by ctd-pitt

2024-11-07 20:51 UTC, prebish commented
Update for reading force data

2024-11-08 00:03 UTC, Kakcalu13 requested changes

2024-11-08 00:03 UTC, Kakcalu13 commented on embodiments/mujoco/controller.py
> +def get_servo_min_max(index):
You don’t need this function. Just access it like this:

`capabilities[output][servo][#][max_value]` and `capabilities[output][servo][#][min_value]`.

'#' is from iteration loop.

You already have this line in your code:

`capabilities = config['capabilities'].copy()`

2024-11-08 00:03 UTC, Kakcalu13 commented on embodiments/mujoco/controller.py
> +def check_keypos(data, model):
what is this for?

2024-11-08 00:03 UTC, Kakcalu13 commented on embodiments/mujoco/controller.py
> +    if obtained_data:
remove this section to avoid spam print

2024-11-08 00:03 UTC, Kakcalu13 commented on embodiments/mujoco/controller.py
> +        print("servo position data d: %d", recieve_servo_position_data) #testing
remove this line as well

2024-11-08 00:03 UTC, Kakcalu13 commented on embodiments/mujoco/controller.py
> +        print("servo data d: %d", recieve_servo_data) #testing
remove this too

2024-11-08 00:03 UTC, Kakcalu13 commented on embodiments/mujoco/controller.py
> +                print(f"Contact between body {contact.geom1} and body {contact.geom2}")
remove prints

2024-11-08 00:03 UTC, Kakcalu13 commented on embodiments/mujoco/test_mujoco.py
What is the difference between this and controller.py?

2024-11-08 00:03 UTC, Kakcalu13 commented on embodiments/mujoco/frame_data_test.py
We need to figure how to integrate this somehow and using the original viewer

2024-11-08 18:11 UTC, ctd-pitt commented on embodiments/mujoco/controller.py
> +def get_servo_min_max(index):
ok, I don't even use it anymore since we changed the actuators to position

2024-11-08 18:14 UTC, ctd-pitt commented on embodiments/mujoco/controller.py
> +def check_keypos(data, model):
for when I was testing how to keep the model standing, I wanted a way to reset the model back to a custom keypos instead of the default one. Don't really need it anymore

2024-11-09 23:48 UTC, prebish commented on embodiments/mujoco/controller.py
> +RUNTIME = 6000 # (seconds) //timeout time
Not 100% sure, but we can try to do a large number in a style like `1e9` or use `float('inf')` but the latter isnt always supported by things.

2024-11-11 17:35 UTC, merged